### ISSUE TITLE
Did I beat the game?

### ISSUE THREAD

**Issue by MoritzGoeckel** [lianmakesthings/click-a-band#1]
![image](https://cloud.githubusercontent.com/assets/9058095/22734535/58b1c9fa-edf6-11e6-8532-81a368f45090.png)

Habe dich über den NodeJS ML Talk auf Youtube gefunden

**Comment by lianmakesthings** [comment]
I think you did :)
Wird leider nicht mehr maintained, da ich mittlerweile die Grundprinzipien von Angular verstanden habe ;)
